# name: Deploy to cPanel

# on:
#   push:
#     branches: [ master ]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Deploy dist folder via FTP
#         uses: SamKirkland/FTP-Deploy-Action@4.3.0
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: ./dist/
#           server-dir: /deluxconex.com/  # Directly to root
#           protocol: ftps  # Try with FTPS instead of FTP